development:
  adapter: postgresql
  encoding: utf8
  database: base_development
  username: postgres
  password: root
  template: template0 # Required for UTF8 encoding
 
test:
  adapter: postgresql
  encoding: utf8
  database: base_development
  username: postgres
  password: root
  template: template0 # Required for UTF8 encoding
 
production:
  adapter: postgresql
  encoding: utf8
  database: base_development
  username: postgres
  password: root
  template: template0 # Required for UTF8 encoding
